// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "hQVQPOOOOQO'#Cf'#CfQVQPOOOOQO-E6d-E6d",
  stateData: "q~O]OS~OQPORPOSPOTPOUPOVPOWPOXPO~O",
  goto: "bZPPPPPPPPPP[QQORRQ",
  nodeNames: "⚠ File Instr Comment Label Reg Decimal Binary Hex Char",
  maxTerm: 13,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "&o~RaX^!Wpq!Wwx!{!O!P#m!Q!R$[!R![%_!]!^%g!c!}&O#f#g&a#y#z!W$f$g!W#BY#BZ!W$IS$I_!W$I|$JO!W$JT$JU!W$KV$KW!W&FU&FV!W~!]Y]~X^!Wpq!W#y#z!W$f$g!W#BY#BZ!W$IS$I_!W$I|$JO!W$JT$JU!W$KV$KW!W&FU&FV!W~#ORO;'S#X;'S;=`#d;=`O#X~#[Pwx#_~#dOX~~#gQwx#_;=`<%l#X~#pR!c!}#y#R#S#y#T#o#y~$OSS~!Q![#y!c!}#y#R#S#y#T#o#y~$_Q#U#V$e#l#m$s~$hP!Q!S$k~$pPV~!Q!S$k~$vR!Q![%P!c!i%P#T#Z%P~%URW~!Q![%P!c!i%P#T#Z%P~%dPU~!Q![%_~%lSR~OY%gZ;'S%g;'S;=`%x<%lO%g~%{P;=`<%l%g~&RP!c!}&U~&XP!c!}&[~&aOQ~~&dP!Q![&g~&lPT~!Q![&g",
  tokenizers: [0],
  topRules: {"File":[0,1]},
  tokenPrec: 0
})
