// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  File = 1,
  Instr = 2,
  Comment = 3,
  Label = 4,
  Reg = 5,
  Decimal = 6,
  Binary = 7,
  Hex = 8,
  Char = 9
